package testapp2;
// Generated Oct 20, 2018 11:59:07 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name="employees"
    ,catalog="employees"
)
public class Employees  implements java.io.Serializable {


     private Integer employeeId;
     private String employeeName;
     private String employeeLocation;
     private double employeeSalary;

    public Employees() {
    }

    public Employees(String employeeName, String employeeLocation, double employeeSalary) {
       this.employeeName = employeeName;
       this.employeeLocation = employeeLocation;
       this.employeeSalary = employeeSalary;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="employee_id", unique=true, nullable=false)
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    
    @Column(name="employee_name", nullable=false, length=50)
    public String getEmployeeName() {
        return this.employeeName;
    }
    
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    
    @Column(name="employee_location", nullable=false, length=50)
    public String getEmployeeLocation() {
        return this.employeeLocation;
    }
    
    public void setEmployeeLocation(String employeeLocation) {
        this.employeeLocation = employeeLocation;
    }

    
    @Column(name="employee_salary", nullable=false, precision=22, scale=0)
    public double getEmployeeSalary() {
        return this.employeeSalary;
    }
    
    public void setEmployeeSalary(double employeeSalary) {
        this.employeeSalary = employeeSalary;
    }




}


